name: wp-sbademo
recipe: wordpress
config:
  php: '8.3'
  composer_version: '2.7.7'
  database: mysql:8.0
  webroot: .
  cache: redis
  ssl: false
  via: nginx
  xdebug: false
services:
  appserver:
    build:
      - composer install
tooling:
  set:
    service: appserver
    description: Set up WordPress config file.
    cmd:
      - cp .lando/wp-config-local.php wp-config.php
  sync:
    service: appserver
    description: Sync the local database and uploads with the remote environment.
    cmd:
      - composer install
      - wp cache flush
  wpadmin:
    service: appserver
    description: Set admin password.
    cmd:
      - wp plugin deactivate wordfence-login-security
      - wp user create wpadmin wpadmin@example.com --role=administrator --user_pass=admin
events:
  post-db-import:
    # replace cloud domain with local domain after importing database
    - appserver: wp search-replace 'iasdemo.ussba.io' 'wp-sbademo.lndo.site' && wp cache flush